server:  
  port: 8073
  context-path: /api

spring:  
  application:
    name: gateway-server
 

logging:
  level:
    org.springframework.cloud.netflix.zuul: TRACE
      
zuul:
  routes:  
    service:
      path: /service/**
      sensitiveHeaders:
      serviceId: auth-server
    employees:
      path: /employees/**
      sensitiveHeaders: 
      serviceId: customer-service
      
eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/service/oauth/token
      userAuthorizationUri: http://localhost:9999/service/oauth/authorize
      clientId : spring123
      clientSecret: test
    resource:
      userInfoUri: http://localhost:9999/service/user
      preferTokenInfo: false  
  sessions: ALWAYS 